extends: substitution
message: Consider using '%s' instead of '%s'
level: warning
ignorecase: true
# swap maps tokens in form of bad: good
swap:
    whitelist: allowlist
    blacklist: denylist
    master: main 